# Author settings (optional)
author:
  name: Bezuhlyi Artem
  email: bezart06@gmail.com

# Theme settings (you can change theme later)
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
